---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./paperless/ks.yaml
  - ./n8n/ks.yaml
  - ./forgejo/ks.yaml
  - ./octoeverywhere-bambu-connect/ks.yaml
