---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asterisk-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: asterisk-secrets
    template:
      engineVersion: v2
      data:
        HA_TOKEN: "{{ .HA_TOKEN }}"
  dataFrom:
    - extract:
        key: asterisk
