---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app asterisk
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      asterisk:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.50.0.248/24"]
              }]
        containers:
          app:
            image:
              repository: docker.io/andrius/asterisk
              tag: 18
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    service:
      sip:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.40.0.32"
        ports:
          sip-udp:
            port: 5060
            protocol: UDP
          sip-tcp:
            port: 5060
            protocol: TCP
          websocket:
            port: 8088
            protocol: TCP
          rtp-start:
            port: 10000
            protocol: UDP
          rtp-end:
            port: 10100
            protocol: UDP

    persistence:
      config-pjsip:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /etc/asterisk/pjsip.conf
            subPath: pjsip.conf
            readOnly: true
      config-extensions:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /etc/asterisk/extensions.conf
            subPath: extensions.conf
            readOnly: true
      config-http:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /etc/asterisk/http.conf
            subPath: http.conf
            readOnly: true
