---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app asterisk
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      asterisk:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.50.0.248/24"]
              }]
        containers:
          app:
            image:
              repository: ghcr.io/tech7fox/asterisk-hass-addon
              tag: latest
            env:
              HA_URL: "https://hass.nikola.wtf"
            envFrom:
              - secretRef:
                  name: asterisk-secrets
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    service:
      sip:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.40.0.32"
        ports:
          sip-udp:
            port: 5060
            protocol: UDP
          sip-tcp:
            port: 5060
            protocol: TCP
          websocket:
            port: 8088
            protocol: TCP
          rtp-start:
            port: 10000
            protocol: UDP
          rtp-end:
            port: 10100
            protocol: UDP
          ami:
            port: 5038
            protocol: TCP

    route:
      websocket:
        hostnames:
          - asterisk.${SECRET_DOMAIN}
        parentRefs:
          - name: ${GATEWAY_INTERNAL}
            namespace: ${GATEWAY_NAMESPACE}
            sectionName: ${GATEWAY_SECTION}
        rules:
          - backendRefs:
              - name: asterisk
                port: 8088

    persistence:
      config:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /config/config.json
            subPath: options.json
            readOnly: true
      config-manager:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /config/asterisk/custom/manager.conf
            subPath: manager.conf
            readOnly: true
      config-pjsip:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /config/asterisk/custom/pjsip_custom.conf
            subPath: pjsip_custom.conf
            readOnly: true
      config-extensions:
        type: configMap
        name: asterisk-config
        globalMounts:
          - path: /etc/asterisk/extensions.conf
            subPath: extensions_custom.conf
            readOnly: true
