---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: asterisk-config
    files:
      - config/pjsip.conf
      - config/extensions.conf
      - config/http.conf
generatorOptions:
  disableNameSuffixHash: true
