---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: asterisk-config
    files:
      - config/options.json
      - config/manager.conf
generatorOptions:
  disableNameSuffixHash: true
