---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appdaemon-secrets
  namespace: home
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: appdaemon-secrets
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .TOKEN }}"
  dataFrom:
    - extract:
        key: appdaemon
