---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app asterisk
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/home/asterisk/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home
  wait: false
  interval: 30m
  timeout: 5m
