---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./z2mqtt/ks.yaml
  - ./govee2mqtt/ks.yaml
  - ./esphome/ks.yaml
  - ./go2rtc/ks.yaml
  - ./wyoming-piper/ks.yaml
  - ./wyoming-whisper/ks.yaml
  - ./scrypted/ks.yaml
  - ./mosquitto/ks.yaml
  - ./appdaemon/ks.yaml
  - ./asterisk/ks.yaml
