---
crons:
  - name: "Snapraid touch"
    minute: "0"
    hour: "6"
    job: "/usr/local/bin/snapraid touch -l /var/log/snapraid.touch.log && curl -fsS --retry 3 {{ healthchecks_touch_uri }}"
  - name: "Snapraid sync"
    minute: "10"
    hour: "6"
    job: "/usr/local/bin/snapraid sync -l /var/log/snapraid.sync.log && curl -fsS --retry 3 {{ healthchecks_sync_uri }}"
  - name: "Snapraid scrub"
    minute: "0"
    hour: "8"
    job: "/usr/local/bin/snapraid scrub -p 10 -l /var/log/snapraid.scrub.log && curl -fsS --retry 3 {{ healthchecks_scrub_uri }}"
  - name: "Smartmon Prometheus"
    minute: "*/5"
    job: "bash /opt/scripts/smartmon.sh > /opt/node_exporter/smart_metrics.prom"
