---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitea/gitea
      tag: 1.19.1
      pullPolicy: IfNotPresent

    persistence:
      enabled: true
      existingClaim: gitea-local-data

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        nginx.ingress.kubernetes.io/proxy-body-size: 128m
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Accept-Encoding "";
          sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/gitea/dracula.css"></head>';
          sub_filter_once on;
      hosts:
        - host: &host git.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    service:
      http:
        port: 3000
      ssh:
        type: LoadBalancer
        port: 22
        externalTrafficPolicy: Local
        externalIPs:
          - "${SVC_GITEA_IP}"

    gitea:
      additionalConfigFromEnvs:
        - name: ENV_TO_INI__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: POSTGRES_PASS
        - name: ENV_TO_INI__ADMIN__USERNAME
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: username
        - name: ENV_TO_INI__ADMIN__PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: password
        - name: ENV_TO_INI__ADMIN__EMAIL
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: email
      config:
        APP_NAME: "git@milojevic"
        server:
          SSH_PORT: 22
          SSH_LISTEN_PORT: 22
          SSH_DOMAIN: ssh.git.${SECRET_DOMAIN}
          root_url: "https://git.${SECRET_DOMAIN}"
          MIGRATE: 1000
          MIRROR: 1000
        respository:
          DEFAULT_PRIVATE: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: false
        database:
          DB_TYPE: postgres
          HOST: postgres-rw.development.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
          SCHEMA: public

    postgresql:
      enabled: false
