---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: forgejo-ssh
spec:
  endpoints:
    - dnsName: "ssh.git.nikola.wtf"
      recordType: A
      targets: ["10.40.0.40"]
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
