---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
  namespace: misc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: forgejo-secret
    template:
      engineVersion: v2
      data:
        FORGEJO_SECRET_KEY: "{{ .FORGEJO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: forgejo
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-admin-secret
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      data:
        FORGEJO_ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        FORGEJO_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: forgejo
